### ISSUE TITLE
[FIX] Longer wav files don't work

### ISSUE THREAD

**Issue by Dimev** [Gianclgar/GDScriptAudioImport#1]
As the title suggest, longer wav files stop early.
I figured out that this can be fixed by replacing all << 32 operators with << 24.
This fixes the conversion of 4 bytes to an integer according to this: https://stackoverflow.com/questions/48321184/how-does-the-byte-order-fallacy-code-work#:~:text=endianness,places%20on%20StackOverflow%20as%20well.

**Comment by Gianclgar** [comment]
Fixed. Thanks!

**Comment by Dimev** [comment]
np!
