### ISSUE TITLE
mp3 support

### ISSUE THREAD

**Issue by 4321ba** [Gianclgar/GDScriptAudioImport#4]
Thank you very much for this!
Now that Godot 3.2.4 supports mp3, it would be easy to add mp3 support, it seems to work fine just like with ogg.
I tried this in RC4 and it seems to work just fine: 
insert after the ogg part:

	#if file is mp3
	elif filepath.ends_with(".mp3"):
		var newstream = AudioStreamMP3.new()
		newstream.loop = true #set to false or delet this line if you dont want to loop
		newstream.data = bytes
		return newstream 

It'd be wise to wait until 3.2.4 comes out though. I'll make a pr.

**Comment by Gianclgar** [comment]
Thanks! I lost the look over Godot sonce a few months ago, great to know now it supports mp3! Thanks for it and for the contribution. Merged! :)
