### ISSUE TITLE
The parsed format code is 3, so it doesn't work

### ISSUE THREAD

**Issue by MrEliptik** [Gianclgar/GDScriptAudioImport#7]
Hey, first, thank you for providing such script. 

I've tried to load a .wav file (too big to send here), and the format code that was parsed was 3, so it's not `8_BITS`, `16_BITS` or `IMA_ADPCM`. 

I'm not sure why, but I can provide you with more information or the file if you want to try.

**Comment by SubhadeepG** [comment]
Same thing happened to me. One of my wav file has a format code of 3. Im posting the file.
[canon_fire.zip](https://github.com/Gianclgar/GDScriptAudioImport/files/6587140/canon_fire.zip)
